apiVersion: v1
kind: Namespace
metadata:
  name: exploresg

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: exploresg
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  OAUTH2_JWT_ISSUER_URI: "https://accounts.google.com"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_EXPLORESG: "INFO"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: exploresg
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "exploresguser"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET_KEY: "CHANGE_ME_IN_PRODUCTION"
  OAUTH2_JWT_AUDIENCES: "YOUR_GOOGLE_CLIENT_ID"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exploresg-auth-service
  namespace: exploresg
  labels:
    app: exploresg-auth-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exploresg-auth-service
  template:
    metadata:
      labels:
        app: exploresg-auth-service
        version: v1
    spec:
      containers:
        - name: auth-service
          image: your-registry/exploresg-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service.exploresg.svc.cluster.local:5432/exploresg_auth_db"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: exploresg-auth-service
  namespace: exploresg
  labels:
    app: exploresg-auth-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: exploresg-auth-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: exploresg-auth-service-hpa
  namespace: exploresg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exploresg-auth-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
